# Generated by Django 3.1.12 on 2021-12-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=30)),
                ('project_manager', models.CharField(max_length=30)),
                ('project_start_date', models.DateField()),
            ],
        ),
    ]
