# Generated by Django 3.1.12 on 2021-12-02 01:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=30)),
                ('employee_last_name', models.CharField(max_length=30)),
                ('employee_designation', models.CharField(max_length=30)),
                ('employee_gender', models.CharField(max_length=10)),
                ('employee_contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('employee_manager_id', models.IntegerField()),
                ('employee_email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
