# Generated by Django 3.1.12 on 2021-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211202_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='training',
        ),
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(default=None, null=True, to='employee.Training', verbose_name='Training'),
        ),
    ]
