# Generated by Django 3.1.12 on 2021-12-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20211202_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='training',
            field=models.ManyToManyField(default=None, to='employee.Training'),
        ),
    ]
