# Generated by Django 3.1.12 on 2021-12-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.IntegerField(primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=30)),
                ('training_description', models.CharField(max_length=256)),
                ('training_total_hours', models.IntegerField()),
            ],
        ),
    ]
